# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.2.5

jobs:
  test:
    docker:
      - image: cimg/node:16.14.2
      #- image: cimg/node:lts-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - run: npm install testcafe
      - run: npm install dayjs
      - run: npm install testcafe-reporter-html
      - run: mkdir test-reports
      #- run: npx testcafe chrome:headless No001No002No003.ts --html=test-reports/report.html --self-contained-html
      - run: npx testcafe chrome:headless No001No002No003.ts --reporter html:test-results/file.html
      - store_artifacts:
          path: test-reports/
          destination: test-reports
      - store_test_results:
          path: test-results

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  e2e-test:
    jobs:
      - test
