# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.2.5

jobs:
  test:
    docker:
      - image: cimg/node:16.14.2
      #- image: cimg/node:lts-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - run: 
          name: "preparation"
          command: npm install testcafe;
                   npm install dayjs;
                   npm install testcafe-reporter-html;
                   mkdir -p /tmp/test-results;
                   #mkdir -p tmp/No001No002No003;
      - run: npx testcafe chrome:headless No001No002No003.ts --reporter html:/tmp/test-results/html_report.html,xunit:/tmp/test-results/xml_report.xml
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: artifact-file

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  e2e-test:
    jobs:
      - test
  schedule_workflow:
    triggers:
      - schedule:
          cron: "15 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - test

